project:
  type: website
  output-dir: docs  

website:
  title: "Assignment 1"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Practical 1"
        href: "Day1_Practicals/Practical_1.qmd"
      - text: "Practical 3 (Q4-Q5)"
        href: "Day3_Practicals/Practical3_Submission.qmd"
      - text: "Practical 4"
        href: "Day4_Practicals/Practical_4.qmd"
